
services:

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"


  car-insurance-bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PATH=/root/.local/bin:$PATH
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - ".env"
    volumes:
      - .:/app
    # command: poetry run python -m app.main.py
    # ports:
    #   - "8000:8000"
    depends_on:
      - redis
  


